Component info
redbooth/babel-plugin-react-element-info pull request #1
Opened 2017-05-03 13:53 UTC by fcsonline

2017-05-04 16:15 UTC, saimonmoore requested changes
I don't understand what the changes are here...I see you're overriding to add an extra property but I don't see why. Can you explain it a bit more please?

2017-05-04 16:27 UTC, fcsonline commented
Added.

2017-05-04 16:28 UTC, saimonmoore approved these changes

2017-05-04 16:29 UTC, saimonmoore commented
Cool thanks...

2017-05-04 16:34 UTC, edulan commented
Tests?

2017-05-04 16:37 UTC, sauloperez commented
Lol

2017-05-04 16:37 UTC, saimonmoore commented
loool

2017-05-04 16:37 UTC, fcsonline commented
Policia!!!!

2017-05-04 16:37 UTC, edulan commented
:trollface:

2017-05-16 14:42 UTC, fcsonline commented
Merging...

2017-05-16 14:42 UTC, merged